### PR TITLE
feat(atuin): Allow disabling the postgreSQL subchart and get DSN from an existing secret

### PR DESCRIPTION
**Pull request by BapRx**
Hey,
I created this PR because I already have a postgres installation and I wanted to use it instead of deploying a new one.
Let me know if you wish to change anything.

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
Hi @BapRx,
Thanks for your PR!
It looks good to me, but I wanted to check the CI Workflow status. Not sure why it didn't run or requested manual approval from me to get triggered..
Could you please rebase your branch onto `main` to see if it triggers them?
Thanks.

**Comment by BapRx** [comment]
Hi, I just rebased !

**Review by rm3l — CHANGES_REQUESTED** [review]
After testing this PR a little bit further, I think you may need to also conditionally start the `wait-db-service` init container (part of the Deployment spec in [`charts/atuin/templates/deployment.yaml`](https://github.com/rm3l/helm-charts/pull/45/files#diff-7daff40b377e977d3125da15d5d67c84015f44e21646289e67e3afa970912419L31)). Otherwise, this init container will try to connect to the database Service, but won't find if the PostgreSQL dependency is not deployed :

```
$ helm install my-atuin ./charts/atuin/ --set postgresql.enabled=false --set postgresql.auth.existingSecret=my-db
NAME: my-atuin
LAST DEPLOYED: Wed Jul 19 23:40:21 2023
NAMESPACE: helm-charts
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace helm-charts -l "app.kubernetes.io/name=atuin,app.kubernetes.io/instance=my-atuin" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace helm-charts $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8888 to use your application"
  kubectl --namespace helm-charts port-forward $POD_NAME 8888:$CONTAINER_PORT

$ kubectl get pod -w                                                  
NAME                        READY   STATUS     RESTARTS   AGE
my-atuin-6f4646964b-kdt9k   0/1     Init:0/1   0          3m40s

$ kubectl logs my-atuin-6f4646964b-dr9k9 --container wait-db-service                                                                                                                           
Server:    10.43.0.10                                                                                                                                                                          
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local                                                                                                                                   
                                                                                                                                                                                               
nslookup: can't resolve 'my-atuin-postgresql.helm-charts.svc.cluster.local'                                                                                                                    
waiting for my-atuin-postgresql.helm-charts.svc.cluster.local                                                                                                                                  
nslookup: can't resolve 'my-atuin-postgresql.helm-charts.svc.cluster.local'                                                                                                                    
Server:    10.43.0.10                                                                                                                                                                          
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local                                                                                                                                   
                                                             
```

**Comment by BapRx** [comment]
Nice catch, I totally missed it! I added a condition around the initContainer.

**Review by rm3l — APPROVED** [review]
Thanks for this!

**Pull request merged**
